name: Deploy to ECS
description: Applies a given task definition to a running service

inputs:
  task-definition:
    description: "Task Definition file"
    required: true
  service:
    description: "Service to deploy"
    required: true
  cluster:
    description: "The cluster where the service is located"
    required: true
  aws_role:
    description: "AWS role to use"
    required: true
  aws_region:
    description: "AWS region to use"
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ inputs.aws_role }}
        aws-region: ${{ inputs.aws_region }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ inputs.task-definition }}
        service: ${{ inputs.service }}
        cluster: ${{ inputs.cluster }}
        wait-for-service-stability: true
